Requested changes

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,40 +1,49 @@
-name: Deploy
+name: CD
 
 on:
   release:
     types: [published]
 
 jobs:
-  deploy:
+  pipeline:
     runs-on: ubuntu-latest
-    
+
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
-    
-    - name: Get release commit hash
+    - name: checkout-code
+      uses: actions/checkout@v7
+      with:
+        fetch-depth: 0
+
+    - name: get-commit-hash
       run: |
         TAG=${{ github.event.release.tag_name }}
         HASH=$(git rev-list -n 1 $TAG)
-        echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV
         echo "RELEASE_HASH=$HASH" >> $GITHUB_ENV
-        echo "Deploying release: $TAG"
-        echo "Commit hash: $HASH"
-    
-    - name: Setup SSH Agent
-      uses: webfactory/ssh-agent@v0.7.0
+        echo "Release hash: $HASH"
+
+    - name: execute-remote-SSH-commands
+      uses: appleboy/ssh-action@v1
       with:
-        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
-    
-    - name: Deploy to server
-      env:
-        DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}
-        DEPLOY_USER: ${{ vars.DEPLOY_USER }}
-        DEPLOY_PORT: ${{ vars.DEPLOY_PORT }}
-        RELEASE_HASH: ${{ env.RELEASE_HASH }}
-        IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
-        DOCKER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        GITHUB_ACTOR: ${{ github.actor }}
-      run: |
-        chmod +x webhook/deploy.sh
-        ./webhook/deploy.sh
+        host: ${{ vars.DEPLOY_HOST }}
+        username: ${{ vars.DEPLOY_USER }}
+        key: ${{ secrets.SSH_PRIVATE_KEY }}
+        port: ${{ vars.DEPLOY_PORT }}
+        script: |
+          set -e
+
+          echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u Velesikamid --password-stdin
+
+          docker pull ghcr.io/velesikamid/catty-reminders-app:${{ env.RELEASE_HASH }}
+
+          docker stop catty-reminders-app || true
+          docker rm catty-reminders-app || true
+
+          docker run -d --name catty-reminders-app -p 8181:8181 ghcr.io/velesikamid/catty-reminders-app:${{ env.RELEASE_HASH }}
+          sleep 4
+
+          if docker ps | grep -q catty-reminders-app; then
+              echo "Deployment completed successfully"
+          else
+              echo "ERROR: Application failed to start"
+              exit 1
+          fi
